version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app
      - FLASK_ENV=development
      - DATABASE_URL=mysql+pymysql://user:password@db/employee_management
    depends_on:
      - db
    volumes:
      - .:/app

  db:
    image: mariadb:10.5
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: employee_management
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data: